# Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:auditoria_dlq_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console (Para você acessar o banco pelo navegador e tirar o print)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# AWS SQS Configuração
spring.cloud.aws.region.static=us-east-2
spring.cloud.aws.credentials.access-key=${ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${SECRET_KEY}

# A sua fila DLQ recém-criada
queue.dlq-name=arn:aws:sqs:us-east-2:198252713931:T04N_FELIPE_ALEXANDRE_JAGAS_DLQ.fifo